// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: ef2331b7e2
// Version Date: 2020-10-07T23:22:38Z

// Package grpc provides a gRPC client for the Greeter service.
package grpc

import (
	"context"
	"github.com/pkg/errors"
	"google.golang.org/grpc"
	"google.golang.org/grpc/metadata"

	"github.com/go-kit/kit/endpoint"
	grpctransport "github.com/go-kit/kit/transport/grpc"

	// This Service
	pb "base-demo/truss-demo"
	"base-demo/truss-demo/greeter-service/svc"
)

// New returns an service backed by a gRPC client connection. It is the
// responsibility of the caller to dial, and later close, the connection.
func New(conn *grpc.ClientConn, options ...ClientOption) (pb.GreeterServer, error) {
	var cc clientConfig

	for _, f := range options {
		err := f(&cc)
		if err != nil {
			return nil, errors.Wrap(err, "cannot apply option")
		}
	}

	clientOptions := []grpctransport.ClientOption{
		grpctransport.ClientBefore(
			contextValuesToGRPCMetadata(cc.headers)),
	}
	var helloEndpoint endpoint.Endpoint

	{
		helloEndpoint = grpctransport.NewClient(
			conn,
			"protos.Greeter",
			"Hello",
			EncodeGRPCHelloRequest,
			DecodeGRPCHelloResponse,
			pb.HelloResponse{},
			clientOptions...,
		).Endpoint()
	}

	var buyEndpoint endpoint.Endpoint
	{
		buyEndpoint = grpctransport.NewClient(
			conn,
			"protos.Greeter",
			"Buy",
			EncodeGRPCBuyRequest,
			DecodeGRPCBuyResponse,
			pb.HelloResponse{},
			clientOptions...,
		).Endpoint()
	}

	return svc.Endpoints{
		HelloEndpoint: helloEndpoint,
		BuyEndpoint:   buyEndpoint,
	}, nil
}

// GRPC Client Decode

// DecodeGRPCHelloResponse is a transport/grpc.DecodeResponseFunc that converts a
// gRPC hello reply to a user-domain hello response. Primarily useful in a client.
func DecodeGRPCHelloResponse(_ context.Context, grpcReply interface{}) (interface{}, error) {
	reply := grpcReply.(*pb.HelloResponse)
	return reply, nil
}

// DecodeGRPCBuyResponse is a transport/grpc.DecodeResponseFunc that converts a
// gRPC buy reply to a user-domain buy response. Primarily useful in a client.
func DecodeGRPCBuyResponse(_ context.Context, grpcReply interface{}) (interface{}, error) {
	reply := grpcReply.(*pb.HelloResponse)
	return reply, nil
}

// GRPC Client Encode

// EncodeGRPCHelloRequest is a transport/grpc.EncodeRequestFunc that converts a
// user-domain hello request to a gRPC hello request. Primarily useful in a client.
func EncodeGRPCHelloRequest(_ context.Context, request interface{}) (interface{}, error) {
	req := request.(*pb.HelloRequest)
	return req, nil
}

// EncodeGRPCBuyRequest is a transport/grpc.EncodeRequestFunc that converts a
// user-domain buy request to a gRPC buy request. Primarily useful in a client.
func EncodeGRPCBuyRequest(_ context.Context, request interface{}) (interface{}, error) {
	req := request.(*pb.HelloRequest)
	return req, nil
}

type clientConfig struct {
	headers []string
}

// ClientOption is a function that modifies the client config
type ClientOption func(*clientConfig) error

func CtxValuesToSend(keys ...string) ClientOption {
	return func(o *clientConfig) error {
		o.headers = keys
		return nil
	}
}

func contextValuesToGRPCMetadata(keys []string) grpctransport.ClientRequestFunc {
	return func(ctx context.Context, md *metadata.MD) context.Context {
		var pairs []string
		for _, k := range keys {
			if v, ok := ctx.Value(k).(string); ok {
				pairs = append(pairs, k, v)
			}
		}

		if pairs != nil {
			*md = metadata.Join(*md, metadata.Pairs(pairs...))
		}

		return ctx
	}
}
