// Code generated by protoc-gen-go. DO NOT EDIT.
// source: demo.proto

package protos

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HelloRequest1 struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest1) Reset()         { *m = HelloRequest1{} }
func (m *HelloRequest1) String() string { return proto.CompactTextString(m) }
func (*HelloRequest1) ProtoMessage()    {}
func (*HelloRequest1) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca53982754088a9d, []int{0}
}

func (m *HelloRequest1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest1.Unmarshal(m, b)
}
func (m *HelloRequest1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest1.Marshal(b, m, deterministic)
}
func (m *HelloRequest1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest1.Merge(m, src)
}
func (m *HelloRequest1) XXX_Size() int {
	return xxx_messageInfo_HelloRequest1.Size(m)
}
func (m *HelloRequest1) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest1.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest1 proto.InternalMessageInfo

func (m *HelloRequest1) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type HelloResponse1 struct {
	Code                 int64               `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string              `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 *HelloResponseData1 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *HelloResponse1) Reset()         { *m = HelloResponse1{} }
func (m *HelloResponse1) String() string { return proto.CompactTextString(m) }
func (*HelloResponse1) ProtoMessage()    {}
func (*HelloResponse1) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca53982754088a9d, []int{1}
}

func (m *HelloResponse1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloResponse1.Unmarshal(m, b)
}
func (m *HelloResponse1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloResponse1.Marshal(b, m, deterministic)
}
func (m *HelloResponse1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloResponse1.Merge(m, src)
}
func (m *HelloResponse1) XXX_Size() int {
	return xxx_messageInfo_HelloResponse1.Size(m)
}
func (m *HelloResponse1) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloResponse1.DiscardUnknown(m)
}

var xxx_messageInfo_HelloResponse1 proto.InternalMessageInfo

func (m *HelloResponse1) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *HelloResponse1) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *HelloResponse1) GetData() *HelloResponseData1 {
	if m != nil {
		return m.Data
	}
	return nil
}

type HelloResponseData1 struct {
	Greeting             string   `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloResponseData1) Reset()         { *m = HelloResponseData1{} }
func (m *HelloResponseData1) String() string { return proto.CompactTextString(m) }
func (*HelloResponseData1) ProtoMessage()    {}
func (*HelloResponseData1) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca53982754088a9d, []int{2}
}

func (m *HelloResponseData1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloResponseData1.Unmarshal(m, b)
}
func (m *HelloResponseData1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloResponseData1.Marshal(b, m, deterministic)
}
func (m *HelloResponseData1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloResponseData1.Merge(m, src)
}
func (m *HelloResponseData1) XXX_Size() int {
	return xxx_messageInfo_HelloResponseData1.Size(m)
}
func (m *HelloResponseData1) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloResponseData1.DiscardUnknown(m)
}

var xxx_messageInfo_HelloResponseData1 proto.InternalMessageInfo

func (m *HelloResponseData1) GetGreeting() string {
	if m != nil {
		return m.Greeting
	}
	return ""
}

type HelloRequest2 struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest2) Reset()         { *m = HelloRequest2{} }
func (m *HelloRequest2) String() string { return proto.CompactTextString(m) }
func (*HelloRequest2) ProtoMessage()    {}
func (*HelloRequest2) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca53982754088a9d, []int{3}
}

func (m *HelloRequest2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest2.Unmarshal(m, b)
}
func (m *HelloRequest2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest2.Marshal(b, m, deterministic)
}
func (m *HelloRequest2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest2.Merge(m, src)
}
func (m *HelloRequest2) XXX_Size() int {
	return xxx_messageInfo_HelloRequest2.Size(m)
}
func (m *HelloRequest2) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest2.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest2 proto.InternalMessageInfo

func (m *HelloRequest2) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type HelloResponse2 struct {
	Code                 int64               `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string              `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 *HelloResponseData1 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *HelloResponse2) Reset()         { *m = HelloResponse2{} }
func (m *HelloResponse2) String() string { return proto.CompactTextString(m) }
func (*HelloResponse2) ProtoMessage()    {}
func (*HelloResponse2) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca53982754088a9d, []int{4}
}

func (m *HelloResponse2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloResponse2.Unmarshal(m, b)
}
func (m *HelloResponse2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloResponse2.Marshal(b, m, deterministic)
}
func (m *HelloResponse2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloResponse2.Merge(m, src)
}
func (m *HelloResponse2) XXX_Size() int {
	return xxx_messageInfo_HelloResponse2.Size(m)
}
func (m *HelloResponse2) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloResponse2.DiscardUnknown(m)
}

var xxx_messageInfo_HelloResponse2 proto.InternalMessageInfo

func (m *HelloResponse2) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *HelloResponse2) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *HelloResponse2) GetData() *HelloResponseData1 {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*HelloRequest1)(nil), "go.micro.srv.greeter.HelloRequest1")
	proto.RegisterType((*HelloResponse1)(nil), "go.micro.srv.greeter.HelloResponse1")
	proto.RegisterType((*HelloResponseData1)(nil), "go.micro.srv.greeter.HelloResponseData1")
	proto.RegisterType((*HelloRequest2)(nil), "go.micro.srv.greeter.HelloRequest2")
	proto.RegisterType((*HelloResponse2)(nil), "go.micro.srv.greeter.HelloResponse2")
}

func init() { proto.RegisterFile("demo.proto", fileDescriptor_ca53982754088a9d) }

var fileDescriptor_ca53982754088a9d = []byte{
	// 240 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x49, 0xcd, 0xcd,
	0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x49, 0xcf, 0xd7, 0xcb, 0xcd, 0x4c, 0x2e, 0xca,
	0xd7, 0x2b, 0x2e, 0x2a, 0xd3, 0x4b, 0x2f, 0x4a, 0x4d, 0x2d, 0x49, 0x2d, 0x52, 0x52, 0xe6, 0xe2,
	0xf5, 0x48, 0xcd, 0xc9, 0xc9, 0x0f, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x31, 0x14, 0x12, 0xe2,
	0x62, 0xc9, 0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x95, 0x4a,
	0xb8, 0xf8, 0xa0, 0x8a, 0x8a, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0xc1, 0xaa, 0x92, 0xf3, 0x53, 0x20,
	0xaa, 0x98, 0x83, 0xc0, 0x6c, 0x21, 0x01, 0x2e, 0xe6, 0xdc, 0xe2, 0x74, 0x09, 0x26, 0xb0, 0x46,
	0x10, 0x53, 0xc8, 0x86, 0x8b, 0x25, 0x25, 0xb1, 0x24, 0x51, 0x82, 0x59, 0x81, 0x51, 0x83, 0xdb,
	0x48, 0x43, 0x0f, 0x9b, 0x0b, 0xf4, 0x50, 0x4c, 0x76, 0x49, 0x2c, 0x49, 0x34, 0x0c, 0x02, 0xeb,
	0x52, 0x32, 0xe0, 0x12, 0xc2, 0x94, 0x13, 0x92, 0xe2, 0xe2, 0x00, 0xeb, 0xcc, 0xcc, 0x4b, 0x87,
	0xba, 0x11, 0xce, 0x47, 0xf7, 0x8c, 0x11, 0x51, 0x9e, 0x31, 0xa2, 0x87, 0x67, 0x8c, 0xb6, 0x30,
	0x72, 0xb1, 0xb8, 0xa4, 0xe6, 0xe6, 0x0b, 0x85, 0x72, 0xb1, 0x81, 0x15, 0x19, 0x09, 0x29, 0xe3,
	0x35, 0x02, 0x12, 0x1d, 0x52, 0x2a, 0x44, 0xd8, 0x63, 0xa8, 0xc4, 0x00, 0x37, 0xd6, 0x90, 0x18,
	0x63, 0x8d, 0x88, 0x32, 0xd6, 0x48, 0x89, 0xc1, 0x89, 0x23, 0x8a, 0x0d, 0x9c, 0x7a, 0x8a, 0x93,
	0x20, 0xb4, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xd5, 0x83, 0xa6, 0xc6, 0x53, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DemoClient is the client API for Demo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DemoClient interface {
	Hello2(ctx context.Context, in *HelloRequest1, opts ...grpc.CallOption) (*HelloResponse1, error)
	Hello1(ctx context.Context, in *HelloRequest2, opts ...grpc.CallOption) (*HelloResponse2, error)
}

type demoClient struct {
	cc *grpc.ClientConn
}

func NewDemoClient(cc *grpc.ClientConn) DemoClient {
	return &demoClient{cc}
}

func (c *demoClient) Hello2(ctx context.Context, in *HelloRequest1, opts ...grpc.CallOption) (*HelloResponse1, error) {
	out := new(HelloResponse1)
	err := c.cc.Invoke(ctx, "/go.micro.srv.greeter.Demo/Hello2", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *demoClient) Hello1(ctx context.Context, in *HelloRequest2, opts ...grpc.CallOption) (*HelloResponse2, error) {
	out := new(HelloResponse2)
	err := c.cc.Invoke(ctx, "/go.micro.srv.greeter.Demo/Hello1", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DemoServer is the server API for Demo service.
type DemoServer interface {
	Hello2(context.Context, *HelloRequest1) (*HelloResponse1, error)
	Hello1(context.Context, *HelloRequest2) (*HelloResponse2, error)
}

func RegisterDemoServer(s *grpc.Server, srv DemoServer) {
	s.RegisterService(&_Demo_serviceDesc, srv)
}

func _Demo_Hello2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest1)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DemoServer).Hello2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/go.micro.srv.greeter.Demo/Hello2",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DemoServer).Hello2(ctx, req.(*HelloRequest1))
	}
	return interceptor(ctx, in, info, handler)
}

func _Demo_Hello1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest2)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DemoServer).Hello1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/go.micro.srv.greeter.Demo/Hello1",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DemoServer).Hello1(ctx, req.(*HelloRequest2))
	}
	return interceptor(ctx, in, info, handler)
}

var _Demo_serviceDesc = grpc.ServiceDesc{
	ServiceName: "go.micro.srv.greeter.Demo",
	HandlerType: (*DemoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hello2",
			Handler:    _Demo_Hello2_Handler,
		},
		{
			MethodName: "Hello1",
			Handler:    _Demo_Hello1_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "demo.proto",
}
